Repository davep/braindrop, pull requests merged in 2025-09, with the labels that each got.

#172 Fixes #171 — Unescaped titles in bookmarks causing braindrop to crash
  src/braindrop/app/widgets/raindrop_details.py
Labels: Bug, Priority: High

#175 Make compact mode even more compact
  ChangeLog.md
  src/braindrop/app/widgets/raindrops_view.py
Labels: Enhancement, TODO, Cosmetic

#177 Pin to textual-enhanced v1.0.0 or later
  pyproject.toml
  uv.lock
Labels: Housekeeping
