Repository davep/braindrop, pull requests merged in 2025-01, with the labels that each got.

#8 Link to the add/edit/delete PR in the warning
  README.md
Labels: Documentation

#10 Add tests for Raindrops
  tests/unit/test_raindrops.py
Labels: Enhancement

#2 Add Raindrop management
  .sandbox/README.md
  .sandbox/create_new_raindrop.py
  .sandbox/delete_a_raindrop.py
  .sandbox/get_suggestions.py
  .sandbox/update_a_raindrop.py
  ChangeLog.md
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  src/braindrop/app/commands/main.py
  src/braindrop/app/data/local.py
  src/braindrop/app/messages/__init__.py
  src/braindrop/app/messages/commands.py
  src/braindrop/app/screens/main.py
  src/braindrop/app/screens/raindrop_input.py
  src/braindrop/app/suggestions/__init__.py
  src/braindrop/app/suggestions/tags.py
  src/braindrop/app/widgets/navigation.py
  src/braindrop/app/widgets/raindrops_view.py
  src/braindrop/raindrop/__init__.py
  src/braindrop/raindrop/api.py
  src/braindrop/raindrop/collection.py
  src/braindrop/raindrop/raindrop.py
  src/braindrop/raindrop/suggestions.py
  src/braindrop/raindrop/tag.py
  src/braindrop/raindrop/time_tools.py
  src/braindrop/raindrop/user.py
  tests/unit/test_raindrop.py
  tests/unit/test_raindrops.py
  tests/unit/test_tag_suggestions.py
  tests/unit/test_tags.py
Labels: Enhancement, Raindrop Feature

#14 Keep mypy happy
  src/braindrop/app/screens/raindrop_input.py
Labels: Enhancement

#16 Remove the warning that it's a read-only client
  README.md
Labels: Documentation

#17 Finish tag suggestion tests
  tests/unit/test_tag_suggestions.py
Labels: Enhancement

#18 Drop ctrl+c as a quit key
  src/braindrop/app/messages/commands.py
Labels: Enhancement

#20 Tidy a docstring in Tag
  src/braindrop/raindrop/tag.py
Labels: Documentation, Housekeeping

#21 Reduce the chance of errors related to non-urly URLs
  ChangeLog.md
  src/braindrop/app/screens/raindrop_input.py
Labels: Bug, Enhancement

#24 Documentation tweaks
  .images/braindrop-social-banner.png
  CONTRIBUTING.md
  README.md
Labels: Documentation

#25 Check code quality via a GitHub workflow
  .github/workflows/style-lint-and-test.yaml
Labels: Housekeeping

#26 Remove hangover workflow code
  .github/workflows/style-lint-and-test.yaml
Labels: Housekeeping

#27 v0.1.1
  ChangeLog.md
  pyproject.toml
Labels: Housekeeping

#28 Add a README to the .posting directory
  .posting/README.md
Labels: Documentation

#29 Some more workflow tweaks
  .github/workflows/style-lint-and-test.yaml
Labels: Housekeeping

#30 Small changes to the cosmetics of the details panel
  ChangeLog.md
  src/braindrop/app/widgets/raindrop_details.py
Labels: Enhancement

#31 Improve how the age and the tags share their line
  ChangeLog.md
  src/braindrop/app/widgets/raindrops_view.py
Labels: Enhancement

#32 Link changes in ChangeLog to relevant PRs
  ChangeLog.md
Labels: Documentation

#33 Lower the Python requirement from 3.11 to 3.10
  .github/workflows/style-lint-and-test.yaml
  .python-version
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  src/braindrop/app/data/local.py
  src/braindrop/app/screens/downloading.py
  src/braindrop/app/widgets/extended_option_list.py
  src/braindrop/raindrop/api.py
Labels: Housekeeping

#34 Improve the cosmetics of the main panels in the application
  ChangeLog.md
  src/braindrop/app/screens/main.py
  src/braindrop/app/widgets/extended_option_list.py
  src/braindrop/app/widgets/raindrop_details.py
Labels: Enhancement, Cosmetic

#35 Consider the project more stable
  pyproject.toml
Labels: Housekeeping

#36 Parametrize some raindrop test duplication
  tests/unit/test_raindrop.py
Labels: Housekeeping

#37 Display any local data before looking to redownload
  ChangeLog.md
  src/braindrop/app/screens/main.py
Labels: Enhancement

#38 v0.2.0
  ChangeLog.md
  pyproject.toml
Labels: Housekeeping

#40 Move the source of "this is local to the app" collection truth into `SpecialCollection`
  .sandbox/ask_for_local_collection.py
  src/braindrop/raindrop/api.py
  src/braindrop/raindrop/collection.py
  tests/unit/test_special_collections.py
Labels: Housekeeping

#41 Test tidying
  src/braindrop/raindrop/raindrop.py
  tests/unit/test_raindrop.py
  tests/unit/test_tag_suggestions.py
  tests/unit/test_tags.py
Labels: Housekeeping

#42 Fix the doubled-up help text in the raindrops details panel
  ChangeLog.md
  src/braindrop/app/widgets/raindrop_details.py
Labels: Bug, Cosmetic

#43 Add link visiting as a global command
  ChangeLog.md
  src/braindrop/app/commands/main.py
  src/braindrop/app/messages/__init__.py
  src/braindrop/app/messages/commands.py
  src/braindrop/app/screens/main.py
  src/braindrop/app/widgets/raindrop_details.py
  src/braindrop/app/widgets/raindrops_view.py
Labels: Enhancement

#44 Simplify the download update
  src/braindrop/app/screens/downloading.py
Labels: Housekeeping

#45 Remove unused import
  src/braindrop/app/widgets/raindrops_view.py
Labels: Housekeeping

#46 Remove unused imports
  src/braindrop/app/widgets/raindrop_details.py
Labels: Housekeeping

#48 More raindrop details in list and detail panel
  ChangeLog.md
  src/braindrop/app/data/local.py
  src/braindrop/app/screens/help.py
  src/braindrop/app/screens/main.py
  src/braindrop/app/widgets/icons.py
  src/braindrop/app/widgets/raindrop_details.py
  src/braindrop/app/widgets/raindrops_view.py
Labels: Enhancement

#49 Ensure locally-held collection of a trashed raindrop is the trash collection
  ChangeLog.md
  src/braindrop/app/data/local.py
  src/braindrop/raindrop/raindrop.py
  tests/unit/test_raindrop.py
Labels: Bug

#51 Make compact mode sticky via configuration
  ChangeLog.md
  src/braindrop/app/data/config.py
  src/braindrop/app/screens/main.py
Labels: Enhancement

#52 v0.3.0
  ChangeLog.md
  pyproject.toml
Labels: Housekeeping

#53 Help screen tweaks
  ChangeLog.md
  src/braindrop/app/screens/help.py
Labels: Enhancement, Cosmetic

#55 Tidy up everything to do with messages, commands and command providers
  src/braindrop/app/commands/__init__.py
  src/braindrop/app/commands/base.py
  src/braindrop/app/commands/commands.py
  src/braindrop/app/messages/__init__.py
  src/braindrop/app/messages/main.py
  src/braindrop/app/providers/__init__.py
  src/braindrop/app/providers/collections.py
  src/braindrop/app/providers/commands_provider.py
  src/braindrop/app/providers/main.py
  src/braindrop/app/providers/tags.py
  src/braindrop/app/screens/help.py
  src/braindrop/app/screens/main.py
  src/braindrop/app/widgets/navigation.py
  src/braindrop/app/widgets/raindrop_details.py
  src/braindrop/app/widgets/raindrops_view.py
Labels: Housekeeping

#56 Use methodcaller over lambda
  src/braindrop/app/screens/help.py
Labels: Housekeeping

#57 Split up the commands
  src/braindrop/app/commands/__init__.py
  src/braindrop/app/commands/collection.py
  src/braindrop/app/commands/commands.py
  src/braindrop/app/commands/filtering.py
  src/braindrop/app/commands/main.py
  src/braindrop/app/commands/raindrop.py
Labels: Housekeeping

#58 Improve the cosmetics of the command palette
  src/braindrop/app/braindrop.py
Labels: Enhancement, Cosmetic

#59 Tidy up configuration updates
  src/braindrop/app/braindrop.py
  src/braindrop/app/data/__init__.py
  src/braindrop/app/data/config.py
  src/braindrop/app/screens/main.py
Labels: Housekeeping

#60 Render notes as Markdown
  ChangeLog.md
  src/braindrop/app/screens/raindrop_input.py
  src/braindrop/app/widgets/raindrop_details.py
Labels: Enhancement

#61 Fix crash when given a child collection sans parent
  ChangeLog.md
  src/braindrop/raindrop/collection.py
Labels: Bug

#62 v0.4.0
  ChangeLog.md
  pyproject.toml
Labels: Housekeeping

#63 Remove unused import
  src/braindrop/app/widgets/raindrops_view.py
Labels: Housekeeping

#65 Ensure the title and the excerpt get escaped
  ChangeLog.md
  src/braindrop/app/widgets/raindrop_details.py
Labels: Bug

#66 Change the background colour of the download busy dialog
  src/braindrop/app/screens/downloading.py
Labels: Cosmetic

#69 Add a local data version check
  src/braindrop/app/data/local.py
  src/braindrop/app/screens/main.py
Labels: Enhancement

#70 Add more work to remove the flash of unneeded scrollbar
  src/braindrop/app/widgets/raindrop_details.py
Labels: Enhancement, Cosmetic

#71 Tweak search tags command
  ChangeLog.md
  src/braindrop/app/commands/filtering.py
Labels: Enhancement

#73 Add collection suggestions to the raindrop dialog
  ChangeLog.md
  src/braindrop/app/screens/raindrop_input.py
Labels: Enhancement, TODO

#75 Add some simple rate limit handling when downloading raindrops
  ChangeLog.md
  src/braindrop/app/data/local.py
  src/braindrop/raindrop/api.py
Labels: Bug, Enhancement

#78 Fix the collection count for groups
  ChangeLog.md
  src/braindrop/app/widgets/navigation.py
Labels: Bug

#82 Add file locations and key files to the README
  README.md
Labels: Documentation

#83 Fix a crash after a redownload after collection removal
  ChangeLog.md
  src/braindrop/app/widgets/raindrop_details.py
Labels: Bug

#84 Refresh images
  .gitignore
  .images/braindrop-help.png
  .images/braindrop.png
Labels: Documentation, Housekeeping

#85 v0.5.0
  ChangeLog.md
  pyproject.toml
Labels: Housekeeping

#91 Fix the count of collections within a group
  ChangeLog.md
  src/braindrop/app/data/local.py
  src/braindrop/app/widgets/navigation.py
Labels: Bug

#96 Adds link and domain to locations of free-text search
  ChangeLog.md
  src/braindrop/raindrop/raindrop.py
  tests/unit/test_raindrop.py
Labels: Enhancement

#97 Ensure various quality checks check tests as well as main source
  Makefile
Labels: Housekeeping

#99 Rework the tag counts
  src/braindrop/app/data/__init__.py
  src/braindrop/app/data/raindrops.py
  src/braindrop/app/providers/tags.py
  src/braindrop/app/suggestions/tags.py
  src/braindrop/app/widgets/navigation.py
  src/braindrop/raindrop/__init__.py
  src/braindrop/raindrop/api.py
  src/braindrop/raindrop/tag.py
  tests/unit/test_raindrops.py
Labels: Enhancement, Housekeeping

#100 Add raindrop types to the navigation panel
  ChangeLog.md
  src/braindrop/app/data/__init__.py
  src/braindrop/app/data/raindrops.py
  src/braindrop/app/messages/__init__.py
  src/braindrop/app/messages/main.py
  src/braindrop/app/screens/main.py
  src/braindrop/app/widgets/navigation.py
Labels: Enhancement, Raindrop Feature

#102 v0.6.0
  ChangeLog.md
  pyproject.toml
Labels: Housekeeping

#103 Various filtering tweaks
  src/braindrop/app/data/raindrops.py
  tests/unit/test_raindrops.py
Labels: Housekeeping

#105 Remove an unused import
  src/braindrop/app/braindrop.py
Labels: Housekeeping

#107 :Remove an unused import
  src/braindrop/app/screens/main.py
Labels: Housekeeping

#106 Handle unknown collections
  ChangeLog.md
  src/braindrop/app/data/local.py
  src/braindrop/app/widgets/navigation.py
Labels: Bug

#109 Tidy a misplaced import
  src/braindrop/app/widgets/navigation.py
Labels: Housekeeping

#110 docs(readme): fix typo
  README.md
Labels: Documentation, Housekeeping

#112 Have Markdown in the help fall back on its container background
  src/braindrop/app/screens/help.py
Labels: Housekeeping

#113 Remove an unused export from screens
  src/braindrop/app/screens/__init__.py
Labels: Housekeeping

#115 Style locally-used tag suggestions different from others
  ChangeLog.md
  src/braindrop/app/screens/raindrop_input.py
Labels: Enhancement, Cosmetic

#116 Link the ChangeLog to the latest PR
  ChangeLog.md
Labels: Documentation, Housekeeping

#118 Tidy commands base class
  src/braindrop/app/commands/base.py
Labels: Housekeeping

#121 Tidy up the way the highlighted raindrop is handled
  src/braindrop/app/screens/main.py
  src/braindrop/app/widgets/raindrops_view.py
Labels: Bug, Enhancement, Housekeeping

#122 Code tidy
  src/braindrop/app/commands/base.py
Labels: Housekeeping

#124 Temporarily disable editing image Raindrops
  ChangeLog.md
  src/braindrop/app/screens/main.py
Labels: Bug, Raindrop Feature

#125 Add a warning to the README about how this isn't a thin client
  README.md
Labels: Documentation, Housekeeping

#128 Don't allow editing of *any* uploaded file
  ChangeLog.md
  src/braindrop/app/screens/main.py
Labels: Bug

#127 Fix a typo in the ChangeLog
  ChangeLog.md
Labels: Documentation, Housekeeping

#129 v0.7.1
  ChangeLog.md
  pyproject.toml
Labels: Housekeeping

#130 Simplify the compose of the main screen
  src/braindrop/app/screens/main.py
Labels: Housekeeping

#131 Tidy the typing around the search input dialog
  src/braindrop/app/screens/search_input.py
Labels: Housekeeping

#132 Code tidying
  src/braindrop/app/screens/main.py
Labels: Housekeeping
